import { Injectable } from '@nestjs/common';
import { In, Repository } from 'typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { District } from '../entity/district.entity';
import { Regions } from '../entity/region.entity';

@Injectable()
export class DistrictsService {
  constructor(
    @InjectRepository(District)
    private districtRepo: Repository<District>,
  ) {}
  getAllDistricts() {
    return this.districtRepo.find({
      relations: ['region'],
      select: ['id', 'name'],
    });
  }

  public async getSelectDistrict(id:number){
    const region=await this.districtRepo.manager.getRepository(Regions).findOne({where:{id:id}}).then((data)=>{
      return data.id
    })
    return this.districtRepo.manager.getRepository(District).find({where:{region:region}})
  }

  public fillDataDistrict = async () => {
    let region_id: any;

    const region = await this.districtRepo.manager
      .getRepository(Regions)
      .findBy({
        id: In([1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14]),
      });
    region.map((data) => {
      region_id = data.id;
    });

    if (this.districtRepo.exist()) {
      const districtArr = [
        { region: region_id, name: 'Amudaryo tumani' },
        { region: region_id, name: 'Beruniy tumani' },
        { region: region_id, name: 'Kegayli tumani' },
        { region: region_id, name: 'Qonliko‘l tumani' },
        { region: region_id, name: 'Qorao‘zak tumani' },
        { region: region_id, name: 'Qo‘ng‘irot tumani' },
        { region: region_id, name: 'Mo‘ynoq tumani' },
        { region: region_id, name: 'Nukus tumani' },
        { region: region_id, name: 'Nukus shahri' },
        { region: region_id, name: 'Taxtako‘pir tumani' },
        { region: region_id, name: 'To‘rtko‘l tumani' },
        { region: region_id, name: 'Xo‘jayli tumani' },
        { region: region_id, name: 'Chimboy tumani' },
        { region: region_id, name: 'Shumanay tumani' },
        { region: region_id, name: 'Ellikqal‘a tumani' },
      ];
      await this.districtRepo.save(districtArr);
    }

    // [
    // {region:region_id,name:"Amudaryo tumani"},
    //     {region:region_id,name:"Beruniy tumani"},
    //     {region:region_id,name:"Kegayli tumani"},
    //     {region:region_id,name:"Qonliko‘l tumani"},
    //     {region:region_id,name:"Qorao‘zak tumani"},
    //     {region:region_id,name:"Qo‘ng‘irot tumani"},
    //     {region:region_id,name:"Mo‘ynoq tumani"},
    //     {region:region_id,name:"Nukus tumani"},
    //     {region:region_id,name:"Nukus shahri"},
    //     {region:region_id,name:"Taxtako‘pir tumani"},
    //     {region:region_id,name:"To‘rtko‘l tumani"},
    //     {region:region_id,name:"Xo‘jayli tumani"},
    //     {region:region_id,name:"Chimboy tumani"},
    //     {region:region_id,name:"Shumanay tumani"},
    //     {region:region_id,name:"Ellikqal‘a tumani"},
    // {"id":"30","region_id":"2","name_uz":"Andijon shahri"},
    // {"id":"31","region_id":"2","name_uz":"Andijon tumani"},
    // {"id":"32","region_id":"2","name_uz":"Asaka tumani"},
    // {"id":"33","region_id":"2","name_uz":"Baliqchi tumani"},
    // {"id":"34","region_id":"2","name_uz":"Buloqboshi tumani"},
    // {"id":"35","region_id":"2","name_uz":"Bo‘z tumani"},
    // {"id":"36","region_id":"2","name_uz":"Jalaquduq tumani"},
    // {"id":"37","region_id":"2","name_uz":"Izbosgan tumani"},
    // {"id":"38","region_id":"2","name_uz":"Qorasuv shahri"},
    // {"id":"39","region_id":"2","name_uz":"Qo‘rg‘ontepa tumani"},
    // {"id":"40","region_id":"2","name_uz":"Marhamat tumani"},
    // {"id":"41","region_id":"2","name_uz":"Oltinko‘l tumani"},
    // {"id":"42","region_id":"2","name_uz":"Paxtaobod tumani"},
    // {"id":"43","region_id":"2","name_uz":"Ulug‘nor tumani"},
    // {"id":"44","region_id":"2","name_uz":"Xonabod tumani"},
    // {"id":"45","region_id":"2","name_uz":"Xo‘jaobod tumani"},
    // {"id":"46","region_id":"2","name_uz":"Shahrixon tumani"},
    // {"id":"47","region_id":"3","name_uz":"Buxoro shahri"},
    // {"id":"48","region_id":"3","name_uz":"Buxoro tumani"},
    // {"id":"49","region_id":"3","name_uz":"Vobkent tumani"},
    // {"id":"50","region_id":"3","name_uz":"G‘ijduvon tumani"},
    // {"id":"51","region_id":"3","name_uz":"Jondor tumani"},
    // {"id":"52","region_id":"3","name_uz":"Kogon tumani"},
    // {"id":"53","region_id":"3","name_uz":"Kogon shahri"},
    // {"id":"54","region_id":"3","name_uz":"Qorako‘l tumani"},
    // {"id":"55","region_id":"3","name_uz":"Qorovulbozor tumani"},
    // {"id":"56","region_id":"3","name_uz":"Olot tumani"},
    // {"id":"57","region_id":"3","name_uz":"Peshku tumani"},
    // {"id":"58","region_id":"3","name_uz":"Romitan tumani"},
    // {"id":"59","region_id":"3","name_uz":"Shofirkon tumani"},
    // {"id":"60","region_id":"4","name_uz":"Arnasoy tumani"},
    // {"id":"61","region_id":"4","name_uz":"Baxmal tumani"},
    // {"id":"62","region_id":"4","name_uz":"G‘allaorol tumani"},
    // {"id":"63","region_id":"4","name_uz":"Do‘stlik tumani"},
    // {"id":"64","region_id":"4","name_uz":"Sh.Rashidov tumani"},
    // {"id":"65","region_id":"4","name_uz":"Jizzax shahri"},
    // {"id":"66","region_id":"4","name_uz":"Zarbdor tumani"},
    // {"id":"67","region_id":"4","name_uz":"Zafarobod tumani"},
    // {"id":"68","region_id":"4","name_uz":"Zomin tumani"},
    // {"id":"69","region_id":"4","name_uz":"Mirzacho‘l tumani"},
    // {"id":"70","region_id":"4","name_uz":"Paxtakor tumani"},
    // {"id":"71","region_id":"4","name_uz":"Forish tumani"},
    // {"id":"72","region_id":"4","name_uz":"Yangiobod tumani"},
    // {"id":"73","region_id":"5","name_uz":"G‘uzor tumani"},
    // {"id":"74","region_id":"5","name_uz":"Dehqonobod tumani"},
    // {"id":"75","region_id":"5","name_uz":"Qamashi tumani"},
    // {"id":"76","region_id":"5","name_uz":"Qarshi tumani"},
    // {"id":"77","region_id":"5","name_uz":"Qarshi shahri"},
    // {"id":"78","region_id":"5","name_uz":"Kasbi tumani"},
    // {"id":"79","region_id":"5","name_uz":"Kitob tumani"},
    // {"id":"80","region_id":"5","name_uz":"Koson tumani"},
    // {"id":"81","region_id":"5","name_uz":"Mirishkor tumani"},
    // {"id":"82","region_id":"5","name_uz":"Muborak tumani"},
    // {"id":"83","region_id":"5","name_uz":"Nishon tumani"},
    // {"id":"84","region_id":"5","name_uz":"Chiroqchi tumani"},
    // {"id":"85","region_id":"5","name_uz":"Shahrisabz tumani"},
    // {"id":"86","region_id":"5","name_uz":"Yakkabog‘ tumani"},
    // {"id":"87","region_id":"6","name_uz":"Zarafshon shahri"},
    // {"id":"88","region_id":"6","name_uz":"Karmana tumani"},
    // {"id":"89","region_id":"6","name_uz":"Qiziltepa tumani"},
    // {"id":"90","region_id":"6","name_uz":"Konimex tumani"},
    // {"id":"91","region_id":"6","name_uz":"Navbahor tumani"},
    // {"id":"92","region_id":"6","name_uz":"Navoiy shahri"},
    // {"id":"93","region_id":"6","name_uz":"Nurota tumani"},
    // {"id":"94","region_id":"6","name_uz":"Tomdi tumani"},
    // {"id":"95","region_id":"6","name_uz":"Uchquduq tumani"},
    // {"id":"96","region_id":"6","name_uz":"Xatirchi tumani"},
    // {"id":"97","region_id":"7","name_uz":"Kosonsoy tumani"},
    // {"id":"98","region_id":"7","name_uz":"Mingbuloq tumani"},
    // {"id":"99","region_id":"7","name_uz":"Namangan tumani"},
    // {"id":"100","region_id":"7","name_uz":"Namangan shahri"},
    // {"id":"101","region_id":"7","name_uz":"Norin tumani"},
    // {"id":"102","region_id":"7","name_uz":"Pop tumani"},
    // {"id":"103","region_id":"7","name_uz":"To‘raqo‘rg‘on tumani"},
    // {"id":"104","region_id":"7","name_uz":"Uychi tumani"},
    // {"id":"105","region_id":"7","name_uz":"Uchqo‘rg‘on tumani"},
    // {"id":"106","region_id":"7","name_uz":"Chortoq tumani"},
    // {"id":"107","region_id":"7","name_uz":"Chust tumani"},
    // {"id":"108","region_id":"7","name_uz":"Yangiqo‘rg‘on tumani"},
    // {"id":"109","region_id":"8","name_uz":"Bulung‘ur tumani"},
    // {"id":"110","region_id":"8","name_uz":"Jomboy tumani"},
    // {"id":"111","region_id":"8","name_uz":"Ishtixon tumani"},
    // {"id":"112","region_id":"8","name_uz":"Kattaqo‘rg‘on tumani"},
    // {"id":"113","region_id":"8","name_uz":"Kattaqo‘rg‘on shahri"},
    // {"id":"114","region_id":"8","name_uz":"Qo‘shrabot tumani"},
    // {"id":"115","region_id":"8","name_uz":"Narpay tumani"},
    // {"id":"116","region_id":"8","name_uz":"Nurabod tumani"},
    // {"id":"117","region_id":"8","name_uz":"Oqdaryo tumani"},
    // {"id":"118","region_id":"8","name_uz":"Payariq tumani"},
    // {"id":"119","region_id":"8","name_uz":"Pastarg‘om tumani"},
    // {"id":"120","region_id":"8","name_uz":"Paxtachi tumani"},
    // {"id":"121","region_id":"8","name_uz":"Samarqand tumani"},
    // {"id":"122","region_id":"8","name_uz":"Samarqand shahri"},
    // {"id":"123","region_id":"8","name_uz":"Toyloq tumani"},
    // {"id":"124","region_id":"8","name_uz":"Urgut tumani"},
    // {"id":"125","region_id":"9","name_uz":"Angor tumani"},
    // {"id":"126","region_id":"9","name_uz":"Boysun tumani"},
    // {"id":"127","region_id":"9","name_uz":"Denov tumani"},
    // {"id":"128","region_id":"9","name_uz":"Jarqo‘rg‘on tumani"},
    // {"id":"129","region_id":"9","name_uz":"Qiziriq tumani"},
    // {"id":"130","region_id":"9","name_uz":"Qo‘mqo‘rg‘on tumani"},
    // {"id":"131","region_id":"9","name_uz":"Muzrabot tumani"},
    // {"id":"132","region_id":"9","name_uz":"Oltinsoy tumani"},
    // {"id":"133","region_id":"9","name_uz":"Sariosiyo tumani"},
    // {"id":"134","region_id":"9","name_uz":"Termiz tumani"},
    // {"id":"135","region_id":"9","name_uz":"Termiz shahri"},
    // {"id":"136","region_id":"9","name_uz":"Uzun tumani"},
    // {"id":"137","region_id":"9","name_uz":"Sherobod tumani"},
    // {"id":"138","region_id":"9","name_uz":"Sho‘rchi tumani"},
    // {"id":"139","region_id":"10","name_uz":"Boyovut tumani"},
    // {"id":"140","region_id":"10","name_uz":"Guliston tumani"},
    // {"id":"141","region_id":"10","name_uz":"Guliston shahri"},
    // {"id":"142","region_id":"10","name_uz":"Mirzaobod tumani"},
    // {"id":"143","region_id":"10","name_uz":"Oqoltin tumani"},
    // {"id":"144","region_id":"10","name_uz":"Sayxunobod tumani"},
    // {"id":"145","region_id":"10","name_uz":"Sardoba tumani"},
    // {"id":"146","region_id":"10","name_uz":"Sirdaryo tumani"},
    // {"id":"147","region_id":"10","name_uz":"Xavos tumani"},
    // {"id":"148","region_id":"10","name_uz":"Shirin shahri"},
    // {"id":"149","region_id":"10","name_uz":"Yangiyer shahri"},
    // {"id":"150","region_id":"11","name_uz":"Angiren shahri"},
    // {"id":"151","region_id":"11","name_uz":"Bekabod tumani"},
    // {"id":"152","region_id":"11","name_uz":"Bekabod shahri"},
    // {"id":"153","region_id":"11","name_uz":"Bo‘ka tumani"},
    // {"id":"154","region_id":"11","name_uz":"Bo‘stonliq tumani"},
    // {"id":"155","region_id":"11","name_uz":"Zangiota tumani"},
    // {"id":"156","region_id":"11","name_uz":"Qibray tumani"},
    // {"id":"157","region_id":"11","name_uz":"Quyichirchiq tumani"},
    // {"id":"158","region_id":"11","name_uz":"Oqqo‘rg‘on tumani"},
    // {"id":"159","region_id":"11","name_uz":"Olmaliq shahri"},
    // {"id":"160","region_id":"11","name_uz":"Ohangaron tumani"},
    // {"id":"161","region_id":"11","name_uz":"Parkent tumani"},
    // {"id":"162","region_id":"11","name_uz":"Piskent tumani"},
    // {"id":"163","region_id":"11","name_uz":"O‘rtachirchiq tumani"},
    // {"id":"164","region_id":"11","name_uz":"Chinoz tumani"},
    // {"id":"165","region_id":"11","name_uz":"Chirchiq shahri"},
    // {"id":"166","region_id":"11","name_uz":"Yuqorichirchiq tumani"},
    // {"id":"167","region_id":"11","name_uz":"Yangiyo‘l tumani"},
    // {"id":"168","region_id":"12","name_uz":"Beshariq tumani"},
    // {"id":"169","region_id":"12","name_uz":"Bog‘dod tumani"},
    // {"id":"170","region_id":"12","name_uz":"Buvayda tumani"},
    // {"id":"171","region_id":"12","name_uz":"Dang‘ara tumani"},
    // {"id":"172","region_id":"12","name_uz":"Yozyovon tumani"},
    // {"id":"173","region_id":"12","name_uz":"Quva tumani"},
    // {"id":"174","region_id":"12","name_uz":"Quvasoy shahri"},
    // {"id":"175","region_id":"12","name_uz":"Qo‘qon shahri"},
    // {"id":"176","region_id":"12","name_uz":"Qo‘shtepa tumani"},
    // {"id":"177","region_id":"12","name_uz":"Marg‘ilon shahri"},
    // {"id":"178","region_id":"12","name_uz":"Oltiariq tumani"},
    // {"id":"179","region_id":"12","name_uz":"Rishton tumani"},
    // {"id":"180","region_id":"12","name_uz":"So‘x tumani"},
    // {"id":"181","region_id":"12","name_uz":"Toshloq tumani"},
    // {"id":"182","region_id":"12","name_uz":"Uchko‘prik tumani"},
    // {"id":"183","region_id":"12","name_uz":"O‘zbekiston tumani"},
    // {"id":"184","region_id":"12","name_uz":"Farg‘ona tumani"},
    // {"id":"185","region_id":"12","name_uz":"Farg‘ona shahri"},
    // {"id":"186","region_id":"12","name_uz":"Furqat tumani"},
    // {"id":"187","region_id":"13","name_uz":"Bog‘ot tumani"},
    // {"id":"188","region_id":"13","name_uz":"Gurlan tumani"},
    // {"id":"189","region_id":"13","name_uz":"Qo‘shko‘pir tumani"},
    // {"id":"190","region_id":"13","name_uz":"Urganch tumani"},
    // {"id":"191","region_id":"13","name_uz":"Urganch shahri"},
    // {"id":"192","region_id":"13","name_uz":"Xiva tumani"},
    // {"id":"193","region_id":"13","name_uz":"Xazarasp tumani"},
    // {"id":"194","region_id":"13","name_uz":"Xonqa tumani"},
    // {"id":"195","region_id":"13","name_uz":"Shavot tumani"},
    // {"id":"196","region_id":"13","name_uz":"Yangiariq tumani"},
    // {"id":"197","region_id":"13","name_uz":"Yangibozor tumani"},
    // {"id":"198","region_id":"14","name_uz":"Bektimer tumani"},
    // {"id":"199","region_id":"14","name_uz":"Mirzo Ulug'bek tumani"},
    // {"id":"200","region_id":"14","name_uz":"Mirobod tumani"},
    // {"id":"201","region_id":"14","name_uz":"Olmazor tumani"},
    // {"id":"202","region_id":"14","name_uz":"Sirg'ali tumani"},
    // {"id":"203","region_id":"14","name_uz":"Uchtepa tumani"},
    // {"id":"204","region_id":"14","name_uz":"Yashnobod tumani"},
    // {"id":"205","region_id":"14","name_uz":"Chilonzor tumani"},
    // {"id":"206","region_id":"14","name_uz":"Shayxontohur tumani"},
    // {"id":"207","region_id":"14","name_uz":"Yunusobod tumani"},
    // {"id":"208","region_id":"14","name_uz":"Yakkasaroy tumani"},
    // {"id":"209","region_id":"1","name_uz":"Taxiatosh shahri"},
    // {"id":"210","region_id":"2","name_uz":"Asaka shahri"},
    // {"id":"211","region_id":"9","name_uz":"Bandixon tumani"},
    // {"id":"212","region_id":"11","name_uz":"Ohangaron shahri"},
    // {"id":"213","region_id":"11","name_uz":"Yangiyo‘l shahri"},
    // {"id":"215","region_id":"11","name_uz":"Toshkent tumani"},
    // {"id":"216","region_id":"13","name_uz":"Xiva shahri"},
    // {"id":"217","region_id":"13","name_uz":"Do'stlik shahri"},
    // {"id":"218","region_id":"14","name_uz":"Yangihayot tumani"},
    // {"id":"219","region_id":"13","name_uz":"Tuproqqala tumani"},
    // {"id":"220","region_id":"7","name_uz":"Davlatobod tumani"},
    // {"id":"221","region_id":"6","name_uz":"G‘ozg‘on shahri"},
    // {"id":"222","region_id":"1","name_uz":"Bo‘zatov tumani"},
    // {"id":"224","region_id":"5","name_uz":"Shahrisabz shahri"},
    // {"id":"225","region_id":"5","name_uz":"Ko‘kdala tumani"}
    // ]
  };
}
